name: "Build and Push to GHCR"
on:
  push:
    branches:
      - main
env:
  working-directroy: ./
jobs:
  GHCR:
    runs-on: ubuntu-latest
    permissions:
       contents: read
       packages: write
    steps:
       - name: Check out the repo
         uses: actions/checkout@v4

       - name: 'Login to GitHub Container Registry'
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           username: ${{secrets.USERNAME}}
           password: ${{secrets.TOKEN}}

       - name: 'Build Inventory Image'
         run: |
             docker build . --tag ghcr.io/yohann30elias/uek210auft43extrawurst:latest
             docker push ghcr.io/yohann30elias/uek210auft43extrawurst:latest
